### ISSUE TITLE
What are some gut cutoff points for when to create new object?

### ISSUE THREAD

**Issue by smccord** [JER-data-team/data.team#4]

**Comment by nstauffer** [comment]
I have thoughts! But I'm not sure if the question at hand is about when to write out intermediate objects, which intermediate objects need to be created in the environment (instead of just being created in a set of function calls but never stored), or to set some kinds of limits on how many objects we make in the environment.

**Comment by smccord** [comment]
more the former (when to write an intermediate object) and what to call it
(rather than data_b), and any other rules of thumb!

**Comment by nstauffer** [comment]
My gut response (certainly not my list of demands!) is:

1. Any time you create a computationally intensive object that takes significantly less time to read back in than to recreate
2. Any time you create an intermediate object that makes sense as a possible input for another task
  - This is a good way to think about where to break up functions, I think. If you're making this intermediate object, maybe that process should be a function unto itself that you can use in a larger and more complex function
3. Names?????
  - Base of name is object "function" like "data" or "points" or "boundary"
  - String on the modifiers, but if there's a purpose change maybe start over? That way we can kind of trace lineage *e.g.* points_restricted > points_restricted_tall > points_benchmarked > points_benchmarked_restricted
  - Always include the date at the end of the filename when writing it out but never use "final"
